/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CompulsoryContractDAO;
import dao.CustomerDAO;
import dao.VoluntaryContractDAO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Account;
import model.CompulsoryContract;
import model.Customer;
import model.VoluntaryContract;

/**Financial problem
 *
 * @author nttungg
 */
public class CancelContractFrame extends javax.swing.JFrame {
    private Customer customer;
    /**
     * Creates new form CancelContractFrame
     */
    public CancelContractFrame() {
        initComponents();
        setLocationRelativeTo(null); 
    }

      public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Customer getCustomer() {
        return customer;
    }
    
    public void initData(Customer cus) {
        if (cus != null) {
             lbName.setText(cus.name);
             lbDob.setText(cus.dob);
             lbSIN.setText(cus.socialInsuranceNo);
             if (cus.compulsoryContract != null) {
                 lbStartedDate.setText(cus.compulsoryContract.startedDate);
             } else if (cus.voluntaryContract != null) {
                 lbStartedDate.setText(cus.voluntaryContract.startedDate);
             } 
        }
    }
    
    public String getDescriptions() {
        String description = "";
        if (cbCompany.isSelected()) {
            description = description + "Company problem ";
        } 
        if (cbFinancial.isSelected()) {
            description = description + "Financial problem ";
        }
        if (cbPolicy.isSelected()) {
            description = description + "Policy problem ";
        }
        if (!taReason.getText().equals("")) {
             description = description + taReason.getText();
        }
        return description;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbFinancial = new javax.swing.JCheckBox();
        cbPolicy = new javax.swing.JCheckBox();
        cbCompany = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taReason = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbAgree = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbDob = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbSIN = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbStartedDate = new javax.swing.JLabel();
        lbMessage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Cancel Contract");

        jLabel2.setText("Cancel Reason :");

        cbFinancial.setText("Financial problem");
        cbFinancial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFinancialActionPerformed(evt);
            }
        });

        cbPolicy.setText("Policy problem");

        cbCompany.setText("Company problem");

        jLabel3.setText("Ohther Reason:");

        jButton1.setText("Cancel Contract");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        taReason.setColumns(20);
        taReason.setRows(5);
        jScrollPane3.setViewportView(taReason);

        jLabel6.setText("Money :");

        jLabel7.setText("0");

        cbAgree.setText("I agree with all the T&C and I want to cancel this contract");

        jLabel8.setText("Name: ");

        lbName.setText("Tung Nguyen");

        jLabel10.setText("Date Of Birth :");

        lbDob.setText("20/2/2019");

        jLabel12.setText("Social Insurance Number :");

        lbSIN.setText("0000000");

        jLabel14.setText("Started Date :");

        lbStartedDate.setText("20/2/2019");

        lbMessage.setText("No message");
        lbMessage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setText("Message:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(cbFinancial)
                                        .addGap(31, 31, 31)
                                        .addComponent(cbPolicy)
                                        .addGap(26, 26, 26)
                                        .addComponent(cbCompany))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(28, 28, 28)
                                        .addComponent(lbName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbDob)))
                                .addGap(151, 151, 151)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbStartedDate))
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbSIN))
                            .addComponent(cbAgree)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(lbMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButton1)
                        .addGap(88, 88, 88)
                        .addComponent(jButton2)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbName)
                    .addComponent(jLabel12)
                    .addComponent(lbSIN))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbDob)
                    .addComponent(jLabel14)
                    .addComponent(lbStartedDate))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbFinancial)
                    .addComponent(cbPolicy)
                    .addComponent(cbCompany))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addComponent(cbAgree)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFinancialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFinancialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFinancialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!cbAgree.isSelected()) {
            lbMessage.setText("You must agree with all the T&C");
            lbMessage.setForeground(Color.RED);
        } else {
            int result = JOptionPane.showConfirmDialog(null, "Are you sure want to cancel your contract? This action may affect your future benefit in insurance", "Message", JOptionPane.PLAIN_MESSAGE);
            int row = -1;
            if (result == JOptionPane.OK_OPTION) {
               if (customer.compulsoryContract != null) {
                    CompulsoryContract compulsoryContract = customer.compulsoryContract;
                    compulsoryContract.state = 2;
                    compulsoryContract.description = getDescriptions();
                    row = CompulsoryContractDAO.updateCompulsoryContract(compulsoryContract);
                } else if (customer.voluntaryContract != null) {
                    VoluntaryContract voluntaryContract = customer.voluntaryContract;
                    voluntaryContract.state = 2;
                    voluntaryContract.description = getDescriptions();
                    row = VoluntaryContractDAO.updateVoluntaryContract(voluntaryContract);
                }
                if (row != 0 && row != -1) {
                    lbMessage.setText("Your request is being processed. Please wait 1-2 days for your confirmation. Thank you for using our insurance service!");
                    lbMessage.setForeground(Color.BLACK);
                } 
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        CustomerMain customerMain = new CustomerMain();
        customerMain.setAcc(this.getCustomer().account);
        customerMain.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelContractFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelContractFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelContractFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelContractFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelContractFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAgree;
    private javax.swing.JCheckBox cbCompany;
    private javax.swing.JCheckBox cbFinancial;
    private javax.swing.JCheckBox cbPolicy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbDob;
    private javax.swing.JLabel lbMessage;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbSIN;
    private javax.swing.JLabel lbStartedDate;
    private javax.swing.JTextArea taReason;
    // End of variables declaration//GEN-END:variables
}
